version: '3.8'

services:
  classifier:
    build:
      context: ./classifier
    volumes:
      - shared-data:/shared-data
    ports:
      - "8000:8000"

  tesseract:
    build:
      context: ./tesseract
    volumes:
      - shared-data:/shared-data
    ports:
      - "5000:5000"

  nougat:
    build:
      context: ./nougat
    volumes:
      - shared-data:/shared-data
    ports:
      - "6000:6000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  surya:
    build:
      context: ./surya
    volumes:
      - shared-data:/shared-data
    ports:
      - "7000:7000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  orchestrator:
    build:
      context: ./orchestrator
    volumes:
      - shared-data:/shared-data
    ports:
      - "8001:8001"
    depends_on:
      - classifier
      - tesseract
      - nougat
      - surya

volumes:
  shared-data: